
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;


public class BillGeneration extends javax.swing.JFrame  {
   
    public BillGeneration() {
        initComponents();
    }
  
    //JTextArea jTextArea1 = new JTextArea();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String s ;int itemCount =0;
    String a;int cleared = 0;
  
    double SubTotal,Gst,Total,Price;
    
      public void Calculate(double a){
        SubTotal = SubTotal + a;
    Gst = SubTotal*0.12 ;
    Total = SubTotal +Gst;
    SubTotalSection.setText(""+SubTotal);
    GSTSection.setText(""+Gst);
    TotalSection.setText(""+Total);
    
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        ShoePanel00001 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ShoeSize1 = new javax.swing.JComboBox<>();
        AddBtn1 = new javax.swing.JButton();
        ShoeName1 = new javax.swing.JLabel();
        PriceTag = new javax.swing.JLabel();
        ShoePrice1 = new javax.swing.JLabel();
        SizeLabel = new javax.swing.JLabel();
        ShoePanel00002 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AddBtn2 = new javax.swing.JButton();
        ShoeName2 = new javax.swing.JLabel();
        PriceTag2 = new javax.swing.JLabel();
        ShoePrice2 = new javax.swing.JLabel();
        SizeLabel1 = new javax.swing.JLabel();
        ShoeSize2 = new javax.swing.JComboBox<>();
        ShoePanel00003 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        AddBtn3 = new javax.swing.JButton();
        ShoeName3 = new javax.swing.JLabel();
        PriceTag3 = new javax.swing.JLabel();
        ShoePrice3 = new javax.swing.JLabel();
        SizeLabel2 = new javax.swing.JLabel();
        ShoeSize3 = new javax.swing.JComboBox<>();
        ShoePanel00004 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        AddBtn4 = new javax.swing.JButton();
        ShoeName4 = new javax.swing.JLabel();
        PriceTag4 = new javax.swing.JLabel();
        ShoePrice4 = new javax.swing.JLabel();
        SizeLabel3 = new javax.swing.JLabel();
        ShoeSize4 = new javax.swing.JComboBox<>();
        ShoePanel00006 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        AddBtn6 = new javax.swing.JButton();
        ShoeName6 = new javax.swing.JLabel();
        PriceTag7 = new javax.swing.JLabel();
        ShoePrice6 = new javax.swing.JLabel();
        SizeLabel4 = new javax.swing.JLabel();
        ShoeSize6 = new javax.swing.JComboBox<>();
        ShoePanel00007 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        AddBtn7 = new javax.swing.JButton();
        ShoeName7 = new javax.swing.JLabel();
        PriceTag8 = new javax.swing.JLabel();
        ShoePrice7 = new javax.swing.JLabel();
        SizeLabel5 = new javax.swing.JLabel();
        ShoeSize7 = new javax.swing.JComboBox<>();
        ShoePanel00008 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        AddBtn8 = new javax.swing.JButton();
        ShoeName8 = new javax.swing.JLabel();
        PriceTag9 = new javax.swing.JLabel();
        ShoePrice8 = new javax.swing.JLabel();
        SizeLabel6 = new javax.swing.JLabel();
        ShoeSize8 = new javax.swing.JComboBox<>();
        ShoePanel00009 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        AddBtn9 = new javax.swing.JButton();
        ShoeName9 = new javax.swing.JLabel();
        PriceTag10 = new javax.swing.JLabel();
        ShoePrice9 = new javax.swing.JLabel();
        SizeLabel7 = new javax.swing.JLabel();
        ShoeSize9 = new javax.swing.JComboBox<>();
        ShoePanel00010 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        AddBtn10 = new javax.swing.JButton();
        ShoeName10 = new javax.swing.JLabel();
        PriceTag6 = new javax.swing.JLabel();
        ShoePrice10 = new javax.swing.JLabel();
        SizeLabel8 = new javax.swing.JLabel();
        ShoeSize10 = new javax.swing.JComboBox<>();
        ShoePanel00011 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        AddBtn11 = new javax.swing.JButton();
        ShoeName11 = new javax.swing.JLabel();
        PriceTag11 = new javax.swing.JLabel();
        ShoePrice11 = new javax.swing.JLabel();
        SizeLabel9 = new javax.swing.JLabel();
        ShoeSize11 = new javax.swing.JComboBox<>();
        ShoePanel00012 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        AddBtn12 = new javax.swing.JButton();
        ShoeName12 = new javax.swing.JLabel();
        PriceTag12 = new javax.swing.JLabel();
        ShoePrice12 = new javax.swing.JLabel();
        SizeLabel10 = new javax.swing.JLabel();
        ShoeSize12 = new javax.swing.JComboBox<>();
        ShoePanel00015 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AddBtn15 = new javax.swing.JButton();
        PriceTag1 = new javax.swing.JLabel();
        ShoePrice15 = new javax.swing.JLabel();
        SizeLabel13 = new javax.swing.JLabel();
        ShoeSize15 = new javax.swing.JComboBox<>();
        ShoeName15 = new javax.swing.JLabel();
        ShoePanel00013 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        AddBtn13 = new javax.swing.JButton();
        ShoeName13 = new javax.swing.JLabel();
        PriceTag13 = new javax.swing.JLabel();
        ShoePrice13 = new javax.swing.JLabel();
        SizeLabel11 = new javax.swing.JLabel();
        ShoeSize13 = new javax.swing.JComboBox<>();
        ShoePanel00014 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        AddBtn14 = new javax.swing.JButton();
        PriceTag14 = new javax.swing.JLabel();
        ShoePrice14 = new javax.swing.JLabel();
        SizeLabel12 = new javax.swing.JLabel();
        ShoeSize14 = new javax.swing.JComboBox<>();
        ShoeName14 = new javax.swing.JLabel();
        ShoePanel00005 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        AddBtn5 = new javax.swing.JButton();
        ShoeName5 = new javax.swing.JLabel();
        PriceTag5 = new javax.swing.JLabel();
        ShoePrice5 = new javax.swing.JLabel();
        SizeLabel16 = new javax.swing.JLabel();
        ShoeSize5 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TotalSection = new javax.swing.JLabel();
        SubTotalSection = new javax.swing.JLabel();
        GSTSection = new javax.swing.JLabel();
        SubTotalLabel = new javax.swing.JLabel();
        GSTLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        ClearBtn = new javax.swing.JButton();
        PrintBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        Category = new javax.swing.JMenu();
        CasualOptn = new javax.swing.JMenuItem();
        FormalsOptn = new javax.swing.JMenuItem();
        SportsOptn = new javax.swing.JMenuItem();
        CheckBills = new javax.swing.JMenu();
        Calculator = new javax.swing.JMenu();
        Logout = new javax.swing.JMenu();
        GoTo = new javax.swing.JMenu();
        DashboardOptn = new javax.swing.JMenuItem();
        InventoryOptn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel2.setBackground(new java.awt.Color(233, 233, 233));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ShoePanel00001.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00001.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Nike Air Force 1_1800.png"))); // NOI18N
        ShoePanel00001.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        ShoeSize1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00001.add(ShoeSize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        AddBtn1.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn1.setText("ADD");
        AddBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn1ActionPerformed(evt);
            }
        });
        ShoePanel00001.add(AddBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName1.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName1.setText("Nike Air Force 1");
        ShoeName1.setOpaque(true);
        ShoePanel00001.add(ShoeName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 20));

        PriceTag.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag.setText("Price (INR) ");
        PriceTag.setOpaque(true);
        ShoePanel00001.add(PriceTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice1.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        ShoePrice1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice1.setText("1800");
        ShoePrice1.setOpaque(true);
        ShoePanel00001.add(ShoePrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel.setText("Size");
        ShoePanel00001.add(SizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        jPanel2.add(ShoePanel00001, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 220));

        ShoePanel00002.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00002.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Vans canvas_3200.jpg"))); // NOI18N
        ShoePanel00002.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn2.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn2.setText("ADD");
        AddBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn2ActionPerformed(evt);
            }
        });
        ShoePanel00002.add(AddBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName2.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName2.setText("Vans Canvas");
        ShoeName2.setOpaque(true);
        ShoePanel00002.add(ShoeName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 20));

        PriceTag2.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag2.setText("Price (INR) ");
        PriceTag2.setOpaque(true);
        ShoePanel00002.add(PriceTag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice2.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        ShoePrice2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice2.setText("3200");
        ShoePrice2.setOpaque(true);
        ShoePanel00002.add(ShoePrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel1.setText("Size");
        ShoePanel00002.add(SizeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00002.add(ShoeSize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        jPanel2.add(ShoePanel00002, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 180, 220));

        ShoePanel00003.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00003.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Air force jordan_12000.jpg"))); // NOI18N
        ShoePanel00003.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn3.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn3.setText("ADD");
        AddBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn3ActionPerformed(evt);
            }
        });
        ShoePanel00003.add(AddBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName3.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName3.setText("Air Jordan 1");
        ShoeName3.setOpaque(true);
        ShoePanel00003.add(ShoeName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 20));

        PriceTag3.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag3.setText("Price (INR) ");
        PriceTag3.setOpaque(true);
        ShoePanel00003.add(PriceTag3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice3.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice3.setText("12000");
        ShoePrice3.setOpaque(true);
        ShoePanel00003.add(ShoePrice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel2.setText("Size");
        ShoePanel00003.add(SizeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00003.add(ShoeSize3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        jPanel2.add(ShoePanel00003, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 180, 220));

        ShoePanel00004.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00004.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Air jordan 1 high white_8000.jpg"))); // NOI18N
        ShoePanel00004.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn4.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn4.setText("ADD");
        AddBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn4ActionPerformed(evt);
            }
        });
        ShoePanel00004.add(AddBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName4.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName4.setText("Air Jordan High ");
        ShoeName4.setOpaque(true);
        ShoePanel00004.add(ShoeName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 20));

        PriceTag4.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag4.setText("Price (INR) ");
        PriceTag4.setOpaque(true);
        ShoePanel00004.add(PriceTag4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice4.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice4.setText("8000");
        ShoePrice4.setOpaque(true);
        ShoePanel00004.add(ShoePrice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel3.setText("Size");
        ShoePanel00004.add(SizeLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00004.add(ShoeSize4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        jPanel2.add(ShoePanel00004, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 180, 220));

        ShoePanel00006.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00006.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Air jordan 1 low ocean red_42000.jpg"))); // NOI18N
        ShoePanel00006.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn6.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn6.setText("ADD");
        AddBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn6ActionPerformed(evt);
            }
        });
        ShoePanel00006.add(AddBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName6.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName6.setText("Air Jordan 1 Low Ocean Red");
        ShoeName6.setOpaque(true);
        ShoePanel00006.add(ShoeName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 20));

        PriceTag7.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag7.setText("Price (INR) ");
        PriceTag7.setOpaque(true);
        ShoePanel00006.add(PriceTag7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice6.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice6.setText("4200");
        ShoePrice6.setOpaque(true);
        ShoePanel00006.add(ShoePrice6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel4.setText("Size");
        ShoePanel00006.add(SizeLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize6.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00006.add(ShoeSize6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        jPanel2.add(ShoePanel00006, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 180, 220));

        ShoePanel00007.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00007.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Air jordan 1 low santra_26000.jpg"))); // NOI18N
        ShoePanel00007.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn7.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn7.setText("ADD");
        AddBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn7ActionPerformed(evt);
            }
        });
        ShoePanel00007.add(AddBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName7.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName7.setText("Air Jordan 1 Low Santra");
        ShoeName7.setOpaque(true);
        ShoePanel00007.add(ShoeName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 20));

        PriceTag8.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag8.setText("Price (INR) ");
        PriceTag8.setOpaque(true);
        ShoePanel00007.add(PriceTag8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice7.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice7.setText("2600");
        ShoePrice7.setOpaque(true);
        ShoePanel00007.add(ShoePrice7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel5.setText("Size");
        ShoePanel00007.add(SizeLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize7.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00007.add(ShoeSize7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        jPanel2.add(ShoePanel00007, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 180, 220));

        ShoePanel00008.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00008.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Air jordan 1 panda_42000.jpg"))); // NOI18N
        ShoePanel00008.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn8.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn8.setText("ADD");
        AddBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn8ActionPerformed(evt);
            }
        });
        ShoePanel00008.add(AddBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName8.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName8.setText("Air Jordan 1 Panda");
        ShoeName8.setOpaque(true);
        ShoePanel00008.add(ShoeName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 20));

        PriceTag9.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag9.setText("Price (INR) ");
        PriceTag9.setOpaque(true);
        ShoePanel00008.add(PriceTag9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice8.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice8.setText("4200");
        ShoePrice8.setOpaque(true);
        ShoePanel00008.add(ShoePrice8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel6.setText("Size");
        ShoePanel00008.add(SizeLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize8.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00008.add(ShoeSize8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        jPanel2.add(ShoePanel00008, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 180, 220));

        ShoePanel00009.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00009.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Air jordan 3 high red lava_42000.jpg"))); // NOI18N
        ShoePanel00009.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn9.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn9.setText("ADD");
        AddBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn9ActionPerformed(evt);
            }
        });
        ShoePanel00009.add(AddBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName9.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName9.setText("Air Jordan 3");
        ShoeName9.setOpaque(true);
        ShoePanel00009.add(ShoeName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 20));

        PriceTag10.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag10.setText("Price (INR) ");
        PriceTag10.setOpaque(true);
        ShoePanel00009.add(PriceTag10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice9.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice9.setText("3800");
        ShoePrice9.setOpaque(true);
        ShoePanel00009.add(ShoePrice9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel7.setText("Size");
        ShoePanel00009.add(SizeLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize9.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00009.add(ShoeSize9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        jPanel2.add(ShoePanel00009, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 180, 220));

        ShoePanel00010.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00010.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Air jordan 4 Black_70000.jpg"))); // NOI18N
        ShoePanel00010.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn10.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn10.setText("ADD");
        AddBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn10ActionPerformed(evt);
            }
        });
        ShoePanel00010.add(AddBtn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName10.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName10.setText("AIr Jordan 4 ");
        ShoeName10.setOpaque(true);
        ShoePanel00010.add(ShoeName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 20));

        PriceTag6.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag6.setText("Price (INR) ");
        PriceTag6.setOpaque(true);
        ShoePanel00010.add(PriceTag6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice10.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice10.setText("7000");
        ShoePrice10.setOpaque(true);
        ShoePanel00010.add(ShoePrice10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel8.setText("Size");
        ShoePanel00010.add(SizeLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize10.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00010.add(ShoeSize10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        jPanel2.add(ShoePanel00010, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 180, 220));

        ShoePanel00011.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00011.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Air jordan 4 Christmas_53000.jpg"))); // NOI18N
        ShoePanel00011.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn11.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn11.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn11.setText("ADD");
        AddBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn11ActionPerformed(evt);
            }
        });
        ShoePanel00011.add(AddBtn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName11.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName11.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName11.setText("AIr Jordan 4 Christmas");
        ShoeName11.setOpaque(true);
        ShoePanel00011.add(ShoeName11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 20));

        PriceTag11.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag11.setText("Price (INR) ");
        PriceTag11.setOpaque(true);
        ShoePanel00011.add(PriceTag11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice11.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice11.setText("5300");
        ShoePrice11.setOpaque(true);
        ShoePanel00011.add(ShoePrice11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel9.setText("Size");
        ShoePanel00011.add(SizeLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize11.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00011.add(ShoeSize11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        jPanel2.add(ShoePanel00011, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 180, 220));

        ShoePanel00012.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00012.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Air jordan 4 oreo_42000.jpg"))); // NOI18N
        ShoePanel00012.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn12.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn12.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn12.setText("ADD");
        AddBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn12ActionPerformed(evt);
            }
        });
        ShoePanel00012.add(AddBtn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName12.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName12.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName12.setText("AIr Jordan 4 Oreo");
        ShoeName12.setOpaque(true);
        ShoePanel00012.add(ShoeName12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 20));

        PriceTag12.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag12.setText("Price (INR) ");
        PriceTag12.setOpaque(true);
        ShoePanel00012.add(PriceTag12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice12.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice12.setText("4200");
        ShoePrice12.setOpaque(true);
        ShoePanel00012.add(ShoePrice12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel10.setText("Size");
        ShoePanel00012.add(SizeLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize12.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00012.add(ShoeSize12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        jPanel2.add(ShoePanel00012, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 180, 220));

        ShoePanel00015.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00015.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePanel00015.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn15.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn15.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn15.setText("ADD");
        AddBtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn15ActionPerformed(evt);
            }
        });
        ShoePanel00015.add(AddBtn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        PriceTag1.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag1.setText("Price (INR) ");
        PriceTag1.setOpaque(true);
        ShoePanel00015.add(PriceTag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice15.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice15.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice15.setText("1200");
        ShoePrice15.setOpaque(true);
        ShoePanel00015.add(ShoePrice15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel13.setText("Size");
        ShoePanel00015.add(SizeLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize15.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00015.add(ShoeSize15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        ShoeName15.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName15.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName15.setText("Nike Air Force 1");
        ShoeName15.setOpaque(true);
        ShoePanel00015.add(ShoeName15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 20));

        jPanel2.add(ShoePanel00015, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, 180, 220));

        ShoePanel00013.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00013.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Air max sneakers_41000.jpg"))); // NOI18N
        ShoePanel00013.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn13.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn13.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn13.setText("ADD");
        AddBtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn13ActionPerformed(evt);
            }
        });
        ShoePanel00013.add(AddBtn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName13.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName13.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName13.setText("Air Max 3");
        ShoeName13.setOpaque(true);
        ShoePanel00013.add(ShoeName13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 20));

        PriceTag13.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag13.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag13.setText("Price (INR) ");
        PriceTag13.setOpaque(true);
        ShoePanel00013.add(PriceTag13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice13.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice13.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice13.setText("4100");
        ShoePrice13.setOpaque(true);
        ShoePanel00013.add(ShoePrice13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel11.setText("Size");
        ShoePanel00013.add(SizeLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize13.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00013.add(ShoeSize13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        jPanel2.add(ShoePanel00013, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 180, 220));

        ShoePanel00014.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00014.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePanel00014.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn14.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn14.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn14.setText("ADD");
        AddBtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn14ActionPerformed(evt);
            }
        });
        ShoePanel00014.add(AddBtn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        PriceTag14.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag14.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag14.setText("Price (INR) ");
        PriceTag14.setOpaque(true);
        ShoePanel00014.add(PriceTag14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice14.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice14.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice14.setText("1200");
        ShoePrice14.setOpaque(true);
        ShoePanel00014.add(ShoePrice14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel12.setText("Size");
        ShoePanel00014.add(SizeLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize14.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00014.add(ShoeSize14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        ShoeName14.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName14.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName14.setText("Nike Air Force 1");
        ShoeName14.setOpaque(true);
        ShoePanel00014.add(ShoeName14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 20));

        jPanel2.add(ShoePanel00014, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 180, 220));

        ShoePanel00005.setBackground(new java.awt.Color(255, 255, 255));
        ShoePanel00005.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shoeimg/Air jordan 1 low blue breeze_42000.jpg"))); // NOI18N
        ShoePanel00005.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 140));

        AddBtn5.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AddBtn5.setText("ADD");
        AddBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn5ActionPerformed(evt);
            }
        });
        ShoePanel00005.add(AddBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));

        ShoeName5.setBackground(new java.awt.Color(255, 255, 255));
        ShoeName5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ShoeName5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoeName5.setText("Air Jordan 1 low blue Breeze");
        ShoeName5.setOpaque(true);
        ShoePanel00005.add(ShoeName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 20));

        PriceTag5.setBackground(new java.awt.Color(255, 255, 255));
        PriceTag5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PriceTag5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceTag5.setText("Price (INR) ");
        PriceTag5.setOpaque(true);
        ShoePanel00005.add(PriceTag5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        ShoePrice5.setBackground(new java.awt.Color(255, 255, 255));
        ShoePrice5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ShoePrice5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoePrice5.setText("4200");
        ShoePrice5.setOpaque(true);
        ShoePanel00005.add(ShoePrice5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        SizeLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        SizeLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SizeLabel16.setText("Size");
        ShoePanel00005.add(SizeLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        ShoeSize5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        ShoeSize5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13" }));
        ShoePanel00005.add(ShoeSize5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));

        jPanel2.add(ShoePanel00005, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 180, 220));

        jTabbedPane2.addTab("tab1", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane2.addTab("tab2", jPanel3);

        jTabbedPane1.addTab("", jTabbedPane2);

        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel6.setText("Formals");
        jPanel4.add(jLabel6);

        jTabbedPane3.addTab("tab1", jPanel4);
        jTabbedPane3.addTab("tab2", jPanel5);

        jTabbedPane1.addTab("", jTabbedPane3);

        jTabbedPane5.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel16.setText("Sports");
        jPanel8.add(jLabel16);

        jTabbedPane5.addTab("1", jPanel8);
        jTabbedPane5.addTab("2", jPanel9);

        jTabbedPane1.addTab("", jTabbedPane5);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1000, 780));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(15);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 350, 450));

        TotalSection.setBackground(new java.awt.Color(153, 255, 0));
        TotalSection.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        TotalSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalSection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TotalSection.setOpaque(true);
        jPanel6.add(TotalSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 690, 170, 40));

        SubTotalSection.setBackground(new java.awt.Color(255, 255, 255));
        SubTotalSection.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        SubTotalSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubTotalSection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SubTotalSection.setOpaque(true);
        jPanel6.add(SubTotalSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 170, 40));

        GSTSection.setBackground(new java.awt.Color(255, 255, 255));
        GSTSection.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        GSTSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GSTSection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GSTSection.setOpaque(true);
        jPanel6.add(GSTSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, 170, 30));

        SubTotalLabel.setBackground(new java.awt.Color(0, 204, 255));
        SubTotalLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        SubTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubTotalLabel.setText("SubTotal");
        SubTotalLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SubTotalLabel.setOpaque(true);
        jPanel6.add(SubTotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 110, 40));

        GSTLabel.setBackground(new java.awt.Color(0, 204, 255));
        GSTLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        GSTLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GSTLabel.setText("GST");
        GSTLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GSTLabel.setOpaque(true);
        jPanel6.add(GSTLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 110, 30));

        TotalLabel.setBackground(new java.awt.Color(0, 204, 255));
        TotalLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        TotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalLabel.setText("Total(INR)");
        TotalLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TotalLabel.setOpaque(true);
        jPanel6.add(TotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 110, 40));

        ClearBtn.setBackground(new java.awt.Color(255, 0, 0));
        ClearBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });
        jPanel6.add(ClearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 130, 30));

        PrintBtn.setBackground(new java.awt.Color(102, 255, 102));
        PrintBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        PrintBtn.setText("Print");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });
        jPanel6.add(PrintBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 130, 30));

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText(" *********************Store_Name*************************\n       Time 20:53:22 Date : 28 october 2023\n *************************************************************\n   Name                                       Price\n _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  \n");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 120));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 350, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 780));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(124, 30));

        Category.setText("Category");
        Category.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Category.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        CasualOptn.setText("Casuals");
        CasualOptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasualOptnActionPerformed(evt);
            }
        });
        Category.add(CasualOptn);

        FormalsOptn.setText("Formals");
        FormalsOptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormalsOptnActionPerformed(evt);
            }
        });
        Category.add(FormalsOptn);

        SportsOptn.setText("Sports");
        SportsOptn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportsOptnActionPerformed(evt);
            }
        });
        Category.add(SportsOptn);

        jMenuBar1.add(Category);

        CheckBills.setText("Check Bills");
        CheckBills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckBills.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(CheckBills);

        Calculator.setText("Calculator");
        Calculator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Calculator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Calculator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculatorMouseClicked(evt);
            }
        });
        jMenuBar1.add(Calculator);

        Logout.setText("Logout");
        Logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logout.setPreferredSize(new java.awt.Dimension(65, 23));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(Logout);

        GoTo.setText("Go To");
        GoTo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GoTo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GoTo.setPreferredSize(new java.awt.Dimension(61, 23));

        DashboardOptn.setText("Dashboard");
        GoTo.add(DashboardOptn);

        InventoryOptn.setText("Inventory");
        GoTo.add(InventoryOptn);

        jMenuBar1.add(GoTo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    private void AddBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn1ActionPerformed
        s = jTextArea1.getText();
     
        Price = Integer.parseInt(ShoePrice1.getText());
        s = s +"\n"+ShoeName1.getText()+" ("+ShoeSize1.getSelectedItem()+")\n\n\t"+Price+"\n";
        jTextArea1.setText(s);
        Calculate(Price); 
        itemCount++;
    }//GEN-LAST:event_AddBtn1ActionPerformed

    private void AddBtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn15ActionPerformed
        s = jTextArea1.getText();
        Price = Integer.parseInt(ShoePrice15.getText());
        s = s +"\n"+ShoeName15.getText()+" ("+ShoeSize15.getSelectedItem()+")\n\n\t"+Price+"\n";
        jTextArea1.setText(s);
        Calculate(Price);
        itemCount++;
    }//GEN-LAST:event_AddBtn15ActionPerformed

    private void AddBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn2ActionPerformed
         s = jTextArea1.getText(); 
         Price = Integer.parseInt(ShoePrice2.getText());
        s = s +"\n"+ShoeName2.getText()+" ("+ShoeSize2.getSelectedItem()+")\n\n\t "+Price+"\n";
        jTextArea1.setText(s);
        Calculate(Price);
        itemCount++;
    }//GEN-LAST:event_AddBtn2ActionPerformed

    private void AddBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn3ActionPerformed
        s = jTextArea1.getText();
        Price = Integer.parseInt(ShoePrice3.getText());
        s = s +"\n"+ShoeName3.getText()+" ("+ShoeSize3.getSelectedItem()+")\n\n\t "+Price+"\n";
        jTextArea1.setText(s);
        Calculate(Price);
        itemCount++;
    }//GEN-LAST:event_AddBtn3ActionPerformed

    private void AddBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn4ActionPerformed
        s = jTextArea1.getText();
        Price = Integer.parseInt(ShoePrice4.getText());
        s = s +"\n"+ShoeName4.getText()+" ("+ShoeSize4.getSelectedItem()+")\n\n\t "+Price+"\n";
        jTextArea1.setText(s);
        Calculate(Price);
        itemCount++;
    }//GEN-LAST:event_AddBtn4ActionPerformed

    private void AddBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtn10ActionPerformed

    private void AddBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtn6ActionPerformed

    private void AddBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtn7ActionPerformed

    private void AddBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtn8ActionPerformed

    private void AddBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtn9ActionPerformed

    private void AddBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtn11ActionPerformed

    private void AddBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtn12ActionPerformed

    private void AddBtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtn13ActionPerformed

    private void AddBtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtn14ActionPerformed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        
        new LoginPage().setVisible(true);
                dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void AddBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn5ActionPerformed
    s = jTextArea1.getText();
    Price = Integer.parseInt(ShoePrice5.getText());
    s = s +"\n"+ShoeName5.getText()+" ("+ShoeSize5.getSelectedItem()+")\n\n\t"+Price+"\n";
    jTextArea1.setText(s);
    Calculate(Price);
    itemCount++;
    }//GEN-LAST:event_AddBtn5ActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
       jTextArea1.setText("");
       itemCount = 0;
        SubTotal = Total = Gst = 0;
       cleared = 0;
       jTabbedPane1.setVisible(true);
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed
        if(itemCount !=0 && cleared == 0){
        String a = " - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ";
        s = s +"\n"+a+ "\nItems: "+itemCount+" GST: "+Gst+" Total Amt: "+Total+"\n"+a;
        jTextArea1.setText(s);
        printComponenet(jTextArea1);
        itemCount = 0;
        SubTotal = Total = Gst = 0;
        cleared++;
        jTabbedPane1.setVisible(false);
        
        }
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void CalculatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatorMouseClicked
        calc Ca = new calc();
        Ca.setVisible(true);
    }//GEN-LAST:event_CalculatorMouseClicked

    private void CasualOptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasualOptnActionPerformed
        jTabbedPane1.setSelectedComponent(jTabbedPane2);
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_CasualOptnActionPerformed

    private void FormalsOptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormalsOptnActionPerformed
        jTabbedPane1.setSelectedComponent(jTabbedPane3);
        jTabbedPane3.setSelectedIndex(0);
    }//GEN-LAST:event_FormalsOptnActionPerformed

    private void SportsOptnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportsOptnActionPerformed
        jTabbedPane1.setSelectedComponent(jTabbedPane5);
        jTabbedPane5.setSelectedIndex(0);
    }//GEN-LAST:event_SportsOptnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillGeneration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn1;
    private javax.swing.JButton AddBtn10;
    private javax.swing.JButton AddBtn11;
    private javax.swing.JButton AddBtn12;
    private javax.swing.JButton AddBtn13;
    private javax.swing.JButton AddBtn14;
    private javax.swing.JButton AddBtn15;
    private javax.swing.JButton AddBtn2;
    private javax.swing.JButton AddBtn3;
    private javax.swing.JButton AddBtn4;
    private javax.swing.JButton AddBtn5;
    private javax.swing.JButton AddBtn6;
    private javax.swing.JButton AddBtn7;
    private javax.swing.JButton AddBtn8;
    private javax.swing.JButton AddBtn9;
    private javax.swing.JMenu Calculator;
    private javax.swing.JMenuItem CasualOptn;
    private javax.swing.JMenu Category;
    private javax.swing.JMenu CheckBills;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JMenuItem DashboardOptn;
    private javax.swing.JMenuItem FormalsOptn;
    private javax.swing.JLabel GSTLabel;
    private javax.swing.JLabel GSTSection;
    private javax.swing.JMenu GoTo;
    private javax.swing.JMenuItem InventoryOptn;
    private javax.swing.JMenu Logout;
    private javax.swing.JLabel PriceTag;
    private javax.swing.JLabel PriceTag1;
    private javax.swing.JLabel PriceTag10;
    private javax.swing.JLabel PriceTag11;
    private javax.swing.JLabel PriceTag12;
    private javax.swing.JLabel PriceTag13;
    private javax.swing.JLabel PriceTag14;
    private javax.swing.JLabel PriceTag2;
    private javax.swing.JLabel PriceTag3;
    private javax.swing.JLabel PriceTag4;
    private javax.swing.JLabel PriceTag5;
    private javax.swing.JLabel PriceTag6;
    private javax.swing.JLabel PriceTag7;
    private javax.swing.JLabel PriceTag8;
    private javax.swing.JLabel PriceTag9;
    private javax.swing.JButton PrintBtn;
    private javax.swing.JLabel ShoeName1;
    private javax.swing.JLabel ShoeName10;
    private javax.swing.JLabel ShoeName11;
    private javax.swing.JLabel ShoeName12;
    private javax.swing.JLabel ShoeName13;
    private javax.swing.JLabel ShoeName14;
    private javax.swing.JLabel ShoeName15;
    private javax.swing.JLabel ShoeName2;
    private javax.swing.JLabel ShoeName3;
    private javax.swing.JLabel ShoeName4;
    private javax.swing.JLabel ShoeName5;
    private javax.swing.JLabel ShoeName6;
    private javax.swing.JLabel ShoeName7;
    private javax.swing.JLabel ShoeName8;
    private javax.swing.JLabel ShoeName9;
    private javax.swing.JPanel ShoePanel00001;
    private javax.swing.JPanel ShoePanel00002;
    private javax.swing.JPanel ShoePanel00003;
    private javax.swing.JPanel ShoePanel00004;
    private javax.swing.JPanel ShoePanel00005;
    private javax.swing.JPanel ShoePanel00006;
    private javax.swing.JPanel ShoePanel00007;
    private javax.swing.JPanel ShoePanel00008;
    private javax.swing.JPanel ShoePanel00009;
    private javax.swing.JPanel ShoePanel00010;
    private javax.swing.JPanel ShoePanel00011;
    private javax.swing.JPanel ShoePanel00012;
    private javax.swing.JPanel ShoePanel00013;
    private javax.swing.JPanel ShoePanel00014;
    private javax.swing.JPanel ShoePanel00015;
    private javax.swing.JLabel ShoePrice1;
    private javax.swing.JLabel ShoePrice10;
    private javax.swing.JLabel ShoePrice11;
    private javax.swing.JLabel ShoePrice12;
    private javax.swing.JLabel ShoePrice13;
    private javax.swing.JLabel ShoePrice14;
    private javax.swing.JLabel ShoePrice15;
    private javax.swing.JLabel ShoePrice2;
    private javax.swing.JLabel ShoePrice3;
    private javax.swing.JLabel ShoePrice4;
    private javax.swing.JLabel ShoePrice5;
    private javax.swing.JLabel ShoePrice6;
    private javax.swing.JLabel ShoePrice7;
    private javax.swing.JLabel ShoePrice8;
    private javax.swing.JLabel ShoePrice9;
    private javax.swing.JComboBox<String> ShoeSize1;
    private javax.swing.JComboBox<String> ShoeSize10;
    private javax.swing.JComboBox<String> ShoeSize11;
    private javax.swing.JComboBox<String> ShoeSize12;
    private javax.swing.JComboBox<String> ShoeSize13;
    private javax.swing.JComboBox<String> ShoeSize14;
    private javax.swing.JComboBox<String> ShoeSize15;
    private javax.swing.JComboBox<String> ShoeSize2;
    private javax.swing.JComboBox<String> ShoeSize3;
    private javax.swing.JComboBox<String> ShoeSize4;
    private javax.swing.JComboBox<String> ShoeSize5;
    private javax.swing.JComboBox<String> ShoeSize6;
    private javax.swing.JComboBox<String> ShoeSize7;
    private javax.swing.JComboBox<String> ShoeSize8;
    private javax.swing.JComboBox<String> ShoeSize9;
    private javax.swing.JLabel SizeLabel;
    private javax.swing.JLabel SizeLabel1;
    private javax.swing.JLabel SizeLabel10;
    private javax.swing.JLabel SizeLabel11;
    private javax.swing.JLabel SizeLabel12;
    private javax.swing.JLabel SizeLabel13;
    private javax.swing.JLabel SizeLabel16;
    private javax.swing.JLabel SizeLabel2;
    private javax.swing.JLabel SizeLabel3;
    private javax.swing.JLabel SizeLabel4;
    private javax.swing.JLabel SizeLabel5;
    private javax.swing.JLabel SizeLabel6;
    private javax.swing.JLabel SizeLabel7;
    private javax.swing.JLabel SizeLabel8;
    private javax.swing.JLabel SizeLabel9;
    private javax.swing.JMenuItem SportsOptn;
    private javax.swing.JLabel SubTotalLabel;
    private javax.swing.JLabel SubTotalSection;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel TotalSection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
     public void printComponenet(Component component){
  PrinterJob pj = PrinterJob.getPrinterJob();
  pj.setJobName(" Print Component ");

  pj.setPrintable ((Graphics pg, PageFormat pf, int pageNum) -> {
      if (pageNum > 0){
          return Printable.NO_SUCH_PAGE;
      }
      
      Graphics2D g2 = (Graphics2D) pg;
      g2.translate(pf.getImageableX(), pf.getImageableY());
      component.paint(g2);
      return Printable.PAGE_EXISTS;
  });
  if (pj.printDialog() == false)
  return;

  try {
        pj.print();
  } catch (PrinterException ex) {
        // handle exception
  }
}
}
