
import java.awt.Color;



public class Dashboard extends javax.swing.JFrame {
    //Color myBlue = new Color(0, 204, 255);
    //Color myBlue1 = new Color(0,153,255);
    Color myYellow = new Color(255, 204, 51);
    Color myYellow1 = new Color(255, 184, 31);

    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenerateBillBtn = new javax.swing.JButton();
        InventoryBtn = new javax.swing.JButton();
        EmployeeDetailBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GenerateBillBtn.setBackground(new java.awt.Color(255, 204, 51));
        GenerateBillBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        GenerateBillBtn.setText("Generate Bill");
        GenerateBillBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        GenerateBillBtn.setOpaque(true);
        GenerateBillBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GenerateBillBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GenerateBillBtnMouseEntered(evt);
            }
        });
        GenerateBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBillBtnActionPerformed(evt);
            }
        });
        getContentPane().add(GenerateBillBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 330, 60));

        InventoryBtn.setBackground(new java.awt.Color(255, 204, 51));
        InventoryBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        InventoryBtn.setText("Manage Inventory");
        InventoryBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        InventoryBtn.setOpaque(true);
        InventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InventoryBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InventoryBtnMouseEntered(evt);
            }
        });
        InventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(InventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 330, 60));

        EmployeeDetailBtn.setBackground(new java.awt.Color(255, 204, 0));
        EmployeeDetailBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        EmployeeDetailBtn.setText("Manage Employee");
        EmployeeDetailBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        EmployeeDetailBtn.setOpaque(true);
        EmployeeDetailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeeDetailBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeeDetailBtnMouseEntered(evt);
            }
        });
        EmployeeDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeDetailBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EmployeeDetailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 330, 60));

        ExitBtn.setBackground(new java.awt.Color(255, 204, 0));
        ExitBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        ExitBtn.setOpaque(true);
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtnMouseEntered(evt);
            }
        });
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 330, 60));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profileicon2.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 200, 200));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Username :- Vignesh Pai");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 300, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Employee Id :- 1024");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 300, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, 370, 510));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Untitled design copy.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void EmployeeDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeDetailBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeDetailBtnActionPerformed

    private void InventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InventoryBtnActionPerformed

    private void GenerateBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBillBtnActionPerformed
        // TODO add your handling code here:
        new BillGeneration().setVisible(true);
        dispose();
    }//GEN-LAST:event_GenerateBillBtnActionPerformed

    private void GenerateBillBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerateBillBtnMouseEntered
        GenerateBillBtn.setBackground(myYellow1);
    }//GEN-LAST:event_GenerateBillBtnMouseEntered

    private void GenerateBillBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerateBillBtnMouseExited
        GenerateBillBtn.setBackground(myYellow);
    }//GEN-LAST:event_GenerateBillBtnMouseExited

    private void InventoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBtnMouseEntered
        InventoryBtn.setBackground(myYellow1);
    }//GEN-LAST:event_InventoryBtnMouseEntered

    private void InventoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBtnMouseExited
        InventoryBtn.setBackground(myYellow);
    }//GEN-LAST:event_InventoryBtnMouseExited

    private void EmployeeDetailBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeDetailBtnMouseEntered
        EmployeeDetailBtn.setBackground(myYellow1);
    }//GEN-LAST:event_EmployeeDetailBtnMouseEntered

    private void EmployeeDetailBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeDetailBtnMouseExited
        EmployeeDetailBtn.setBackground(myYellow);
    }//GEN-LAST:event_EmployeeDetailBtnMouseExited

    private void ExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseEntered
        ExitBtn.setBackground(myYellow1);
    }//GEN-LAST:event_ExitBtnMouseEntered

    private void ExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseExited
        ExitBtn.setBackground(myYellow);
    }//GEN-LAST:event_ExitBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmployeeDetailBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton GenerateBillBtn;
    private javax.swing.JButton InventoryBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
